server:
  port: 8088
#spring:
#  application:
#    name: flashcard
#  datasource:
#    password: password
#    url: jdbc:h2:mem:memdb
#    username: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
#    show-sql: false
spring:
  application:
    name: flashcard
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
  config:
    import: "optional:configserver:"        