#This is a comment
server:
  port: 8080

spring:
#  datasource:
#    url: ${DB_URL} #can hardcode credentials, but better practice to use environment variables to not expose creds
#    username: ${DB_USER}
#    password: ${DB_PASS}
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
  datasource: 
    url: jdbc:h2:mem:mydb
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  