#server:
#  port: 8080

#spring:#  application:#    name: gateway
#  cloud:#    gateway:#      default-filters:#      - PrefixPath=/
#      routes:
##      - id: flashcard
#        uri: lb://flashcard
#        predicates:#        - Path=/flashcard/**
#        filters:
#        - StripPrefix=1
#      - id: quiz
#        uri: lb://quiz
#        predicates:#        - Path=/quiz/**
#        filters:
#        - StripPrefix=1
spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
  config:
    import: "optional:configserver:"